### ISSUE TITLE
Processor Support

### ISSUE THREAD

**Issue by johnhlaj** [minhng-info/python-benchmark-thread-vs-process#5]
Not really an issue.  Would it be possible to add additional processor support?  I installed TvP 0.1.4 on a ARM Cortex A53 system specifically an OrangePI R1 Plus and got the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/python_benchmark_thread_vs_process", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/python_benchmark_thread_vs_process/main.py", line 62, in run
    out_table[1].append(cpuinfo.cpu.info[0]["model name"])
KeyError: 'model name'
```

Cheers.

**Comment by johnhlaj** [comment]
Removing cpuinfo.cpu.info[0] from the table append and manually entering a model seems to have worked.  I have no clue how to look up an arm cpu model programatically though.

It completes with:


```
Benchmarking (4 CPUs @ 1512MHz) ... please wait...
====================
| BENCHMARK RESULT |
====================

| Num CPUs | CPU Model      | Current CPU Freq (MHz) | Multi-Thread Time (s) | Multi-Process Time (s) | TotalTestOperation 
| 4        | ARM Cortex A53 | 1512                   | 289.2922              | 64.5466                | 400                  |

```
